---

- name: Debugging playbook
  hosts: all
  gather_facts: false
  tasks:

    - name: print out names of all groups
      debug: msg="{{ groups }}"
      run_once: True

    - name: print host name
      debug: msg="{{ ansible_host }}"