---
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - debug:
        msg: "Send message to {{ account_owner }} ({{ account_alias }} rep, account no. {{ account_number }}) that {{ inventory_hostname }} is {{ resolved_state }}"
